name: 'Build DXVK on Update Signal'

on:
  repository_dispatch:
    types: [dxvk-update]

permissions:
  contents: write   # Required to create releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DXVK source
        uses: actions/checkout@v4
        with:
          repository: doitsujin/dxvk
          ref: ${{ github.event.client_payload.commit_sha }}
          path: dxvk_source
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build DXVK
        id: build
        uses: Joshua-Ashton/arch-mingw-github-action@v8
        with:
          command: |
            cd dxvk_source
            cd dxvk_source
            VERSION_NAME="$(git rev-parse --short HEAD)"
            ./package-release.sh "$VERSION_NAME" build --no-package
            echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Prepare Release Assets
        run: |
          mkdir release_assets
          mv dxvk_source/build/dxvk-*/* release_assets/
          cd release_assets
          zip -r "../dxvk-${{ env.VERSION_NAME }}.zip" .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DXVK (${{ env.VERSION_NAME }})"
          tag_name: "dxvk-${{ env.VERSION_NAME }}"
          files: |
            dxvk-${{ env.VERSION_NAME }}.zip
            release_assets/*.tar.gz
          generate_release_notes: true
